// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package definition

import (
	"github.com/Liar233/empty-app/internal/app"
)

// Injectors from wire.go:

func InitApp() app.Application {
	application := app.NewApplication()
	return application
}
